name: CI

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v17
        with:
          java-version: '17'
      - name: Maven Package
        run: mvn -B clean package -tests


  
