# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
  
